### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by IsraaSulaiman** [FACG6/musify#1]
File Structure for our project is as follows:

1-Public

- [ ] pages

- Songs
- myFav

- [ ] css
- style.css

- [ ] js
- dom.js
- fetch.js

- [ ] index.html

2-Src

- [ ] query

- addUser
- checkuser
- getsongs
- getfavorite
- addsong
- addfavorite

- [ ] database
- db_connection.js
- db_build.js
- db_build.sql

- [ ] server.js

- [ ] handler.js

- [ ] router.js

- [ ] cookie.js

- [ ] hashpas.js

3-Testing

- [ ] testserver.js

- [ ] testquery

4-ReadMe

**Comment by AbdallahAmmar96** [comment]
done
